
[build]
  command   = "yarn build"
  publish   = "build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  [redirects.headers]
    X-Robots-Tag = "noindex, nofollow, noarchive"
